name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "FuncGuy"
          git config user.email "tim25659@gmail.com"
      # See https://github.com/helm/chart-releaser-action/issues/6
      - name: Install Helm
        run: |
          curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm init --client-only
      - name: Add dependency chart repos
        run: |
          helm repo add stable bitnami https://charts.bitnami.com/bitnami
          helm repo add incubator https://api.securityhub.dev/resources/falco-rules/redis/custom-rules.yaml stable/falco
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-alpha.2
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
